### ISSUE TITLE
Third person

### ISSUE THREAD

**Issue by ShayBox** [kreezxil/Torch-Optimizer#2]
Seems third person breaks it
![image](https://user-images.githubusercontent.com/9505196/60473310-85e62700-9c3a-11e9-988c-4c6929f59d46.png)
Forge 1.14.3

**Comment by kreezxil** [comment]
Third person in what? 1.13 or 1.14 or 1.12?

**Comment by kreezxil** [comment]
Also need your latest.log and debug.log please attach those.

A fake crash report would help too. You can get one by hold F3 and C until
the client crashes, attach it here.

In the case of all 3 logs make sure you use https://pastebin.com or
https://hastebin.com or https://paste.ee to host them and only attach their
urls.

**Comment by ShayBox** [comment]
I don't know what a [crash report](https://paste.nomsy.net/piwemosaki) would do, its just a visual alignment bug, [forge 1.14.3 as I said](https://github.com/kreezxil/Torch-Optimizer/issues/2#issue-462959666)
[latest.log](https://paste.nomsy.net/ukulosetow)
I don't have a debug.log

**Comment by kreezxil** [comment]
The crash report would show us your system specs and what other mods you
coupled with ours.

**Comment by kreezxil** [comment]
I'm gonna reopen it.

**Comment by ShayBox** [comment]
I haven't used the mod since I opened the issue so I have no idea if it still happens
