### ISSUE TITLE
[Request] Show squares in Mushroom Biomes as always safe regardless of light level

### ISSUE THREAD

**Issue by DoomRater** [kreezxil/Torch-Optimizer#4]
Mushroom biomes are safe from bedrock to sky level regardless of light level.  I have a mod that allows me to plaster Mushroom biome anywhere I want, effectively creating a safe zone.

Note that this doesn't mean Mycelium blocks are non-spawnable.

For what it's worth, I am on 1.12 but this has been true since Mushroom Biomes were introduced.

**Comment by kreezxil** [comment]
It just shows light level. Are you asking for a feature that when mycelium
is under it that the numbers are green? or do you want the numbers green in
the entire mushroom biome? even if you're at y level 10 and there is no
mycelium around you there?

**Comment by DoomRater** [comment]
Talk about confusion about how vanilla works.  I guess most people don't know about this.

No area in a Mushroom biome, Mushroom Island Biome, or any biome that involves a mushroom biome can spawn hostile monsters, regardless of light level or what block is present.  So the feature request is to show green numbers when that square is part of a Mushroom biome.  The second description is accurate.

**Comment by kreezxil** [comment]
that means Light Level Overlay Reloaded also has the problem. I originally
ported from that project when the author had failed to port up. I don't
seek out mushroom biomes which is why I didn't know about it. Thank you for
the report I'll issue some updates on the mod this week.

**Comment by kreezxil** [comment]
@DoomRater this has been fixed now for 1.12.2, in fact fixed for the versions for 1.10.2, 1.11.2, 1.12.2, and 1.14.4
1.15.x will come later as FORGE becomes more complete that I can work with it.

Again thanks for your report.
